Management/ApplicationStoreApplication/Models/ForgotPasswordModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationStoreApplication.Models
{
    public class ForgotPasswordModel
    {
        public string Email { get; set; }
    }
}

Management/ApplicationStoreApplication/Models/PasswordModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationStoreApplication.Models
{
	public class PasswordModel
	{
		public string FirstlastName { get; set; }
		public string OldPassword { get; set; }
		public string NewPassword { get; set; }
		public string ConfirmNewPassword { get; set; }
		public string Message { get; set; }
	}
}

Management/ApplicationStoreApplication/Models/RecoveryPassModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ApplicationStoreApplication.Models
{
    public class RecoveryPassModel
    {
        [Required(ErrorMessage = "Mobile Number is Required")]
        public string Mobile { get; set; }
    }
}

Management/ApplicationStoreApplication/Models/ResetPasswordModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationStoreApplication.Models
{
    public class ResetPasswordModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Code { get; set; }
    }
}

Management/ApplicationStoreApplication/Models/SmsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationStoreApplication.Models
{
    public class SmsModel
    {
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
    }
}

Management/ApplicationStoreApplication/Models/SmsSettingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationStoreApplication.Models
{
    public class SmsSettingModel
    {
        public string Number { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Company { get; set; }
        public string Ip { get; set; }
        public bool IsFlash { get; set; }
        public bool IsFullAct { get; set; }
    }
}

Management/ApplicationStoreApplication/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace ApplicationStoreApplication.Controllers
{
    public class BaseController : Controller
    {
        protected ClaimsPrincipal CurrentUser { get { return User as ClaimsPrincipal; } }
        protected string UserName { get { return CurrentUser.Claims.First(o => o.Type == "name").Value; } }
    }
}

Management/ApplicationStoreApplication/Controllers/HomeController.cs
using Management.Infrastructure.Facade.DTOModel;
using Management.Infrastructure.Facade.FacadeService.Contracts;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace ApplicationStoreApplication.Controllers
{
    public class HomeController : BaseController
    {
        #region Fields

        private IClientFacadeService _clientFacadeService;

        #endregion

        #region Ctor

        public HomeController(IClientFacadeService clientFacadeService)
        {
            _clientFacadeService = clientFacadeService;
        }

        #endregion

        // GET: Home
        public ActionResult Index()
        {
            //List<ClientDTO> temp = _clientFacadeService.GetAllClientsByUserName("Admin").ToList();
            List<ClientDTO> temp = _clientFacadeService.GetAllClientsByUserName(UserName).ToList();
            ViewBag.UserName = this.UserName;
            return View(temp);
        }

        [AllowAnonymous]
        public ActionResult Signout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/");
        }

        [AllowAnonymous]
        public void SignoutCleanup(string sid)
        {
            var cp = (ClaimsPrincipal)User;
            var sidClaim = cp.FindFirst("sid");
            if (sidClaim != null && sidClaim.Value == sid)
            {
                Request.GetOwinContext().Authentication.SignOut("Cookies");
            }
        }
    }
}

Management/ApplicationStoreApplication/Controllers/RecoveryPasswordController.cs
using ApplicationStoreApplication.Models;
using ApplicationStoreApplication.Utility;
using Management.Infrastructure.Facade.FacadeService.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ApplicationStoreApplication.Controllers
{
    
    public class RecoveryPasswordController : Controller
    {
        #region Fields

        private IUserFacadeService _userFacadeService;
        private SmsService _smsService;
        #endregion

        #region Ctor

        public RecoveryPasswordController(IUserFacadeService userFacadeService)
        {
            _userFacadeService = userFacadeService;
            _smsService = new SmsService();
        }

        #endregion
        [AllowAnonymous]
        public ActionResult RecoverPassword()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult RecoverPassword(RecoveryPassModel model)
        {
            var _users = _userFacadeService.GetUsers();
            var _hasUser = _users.Where(u => u.PhoneNumber == model.Mobile).FirstOrDefault();
            if(_hasUser == null)
            {
                ModelState.AddModelError("Mobile", "there is not mobile number");
                return View(model);
            }
           
            var pass = CreatePassword();
            SmsService.ClsSend smsSingle = new SmsService.ClsSend();
            smsSingle.SendSMS_Single(new SmsModel { PhoneNumber = model.Mobile, Message = pass }, SmsSetting.GetConfig());
           _userFacadeService.UpdatePassword(_hasUser.UserProfile.Id, pass);
            return RedirectToAction("Success");

        }

        public string CreatePassword()
        {
            int length = 8;
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder res = new StringBuilder();
            Random rnd = new Random();
            while (0 < length--)
            {
                res.Append(valid[rnd.Next(valid.Length)]);
            }
            return res.ToString();
        }
    }
}

Management/ApplicationStoreApplication/Controllers/UserProfileController.cs
using ApplicationStoreApplication.Models;
using Framework.Core.Contracts.Security;
using Management.Infrastructure.Facade.DTOModel;
using Management.Infrastructure.Facade.FacadeService.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationStoreApplication.Controllers
{
    public class UserProfileController : BaseController
    {
        #region Fields

        private IUserFacadeService _userFacadeService;
		#endregion

		#region Ctor

		public UserProfileController(IUserFacadeService userFacadeService)
        {
            _userFacadeService = userFacadeService;
		}

        #endregion
        // GET: UserProfile
        public ActionResult Index()
        {
            ViewBag.UserName = this.UserName;
            var user = _userFacadeService.FindUserByName(this.UserName);
            return View(user);
        }
		public ActionResult ChangePassword()
		{
			ViewBag.UserName = this.UserName;
			var user = _userFacadeService.FindUserByName(this.UserName);
			//user.FirstName = "ali";
			PasswordModel passwordDto = new Models.PasswordModel { FirstlastName = user.FirstName + ' ' + user.LastName,Message= "تغییر رمز عبور" };
			return View(passwordDto);

		}
		[HttpPost]
		public ActionResult ChangePassword(PasswordModel dto)
		{
			ViewBag.UserName = this.UserName;
			var user = _userFacadeService.FindUserByName(this.UserName);
			PasswordModel passwordDto = new Models.PasswordModel { FirstlastName = user.FirstName + ' ' + user.LastName};
			if(!dto.ConfirmNewPassword.Equals(dto.NewPassword))
			{
				passwordDto.Message = "تکرار رمز عبور اشتباه است";
				return View(passwordDto);
			}
			if (!_userFacadeService.IsSamePassword(user.Id,dto.OldPassword))
			{
				passwordDto.Message = "کلمه عبور اشتباه است";
				return View(passwordDto);
			}
			_userFacadeService.UpdatePassword(user.Id, dto.NewPassword);
			passwordDto.Message = "کلمه عبور با موفقیت به روز رسانی شد";
			return View(passwordDto);

		}
	}
}

Management/ApplicationStoreApplication/Views/Home/Index.cshtml
@model List<Management.Infrastructure.Facade.DTOModel.ClientDTO>
@{
	ViewBag.Title = "Index";
}

<div class="uk-grid uk-grid-width-small-1-2 uk-grid-width-large-1-3 uk-grid-width-xlarge-1-5 uk-text-center uk-sortable sortable-handler" id="dashboard_sortable_cards" data-uk-sortable="" data-uk-grid-margin="">
	@foreach (var item in Model)
	{
		<div>
			<div class="md-card md-card-hover md-card-overlay">
				<div class="md-card-content">
					<div class="epc_chart" data-percent="76" data-bar-color="#03a9f4">
						<span class="epc_chart_icon">
							@if (item.LogoUri.Length!=0)
							{
								<img src="data:image/jpeg;charset=utf-8;base64,@System.Convert.ToBase64String(item.LogoUri)" width="121px" height="121px" />
							}
							else
							{
								<img src="~/Content/assets/img/download.png" alt="@item.ClientName" />
							}
						</span>
						<canvas height="110" width="110"></canvas>
					</div>
				</div>
				<div class="md-card-overlay-content">
					<div class="uk-clearfix md-card-overlay-header">
						<i class="md-icon material-icons md-card-overlay-toggler"></i>
						<h3>
							<a href="@item.ClientUri">@item.ClientName</a>
						</h3>
					</div>
					@item.ClientName;
				</div>
			</div>
		</div>

	}
</div>

Management/ApplicationStoreApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- Remove Tap Highlight on Windows Phone IE -->
	<meta name="msapplication-tap-highlight" content="no" />
	<link rel="icon" type="image/png" href="~/Content/assets/img/favicon-16x16.png" sizes="16x16">
	<link rel="icon" type="image/png" href="~/Content/assets/img/favicon-32x32.png" sizes="32x32">

	<!-- uikit -->
	<link rel="stylesheet" href="~/Content/bower_components/uikit/css/uikit.almost-flat.min.css" media="all">
	<!-- flag icons -->
	<link rel="stylesheet" href="~/Content/assets/icons/flags/flags.min.css" media="all">
	<!-- altair admin -->
	<link rel="stylesheet" href="~/Content/assets/css/main.min.css" media="all">
	<!-- matchMedia polyfill for testing media queries in JS -->
	<!--[if lte IE 9]>
		<script type="text/javascript" src="~/Content/bower_components/matchMedia/matchMedia.js"></script>
		<script type="text/javascript" src="~/Content/bower_components/matchMedia/matchMedia.addListener.js"></script>
	<![endif]-->
	<title>@ViewBag.Title</title>
</head>
<body class="top_menu">
	<!-- main header -->
	<header id="header_main">
		<div class="header_main_content">
			<nav class="uk-navbar">
				<div class="main_logo_top">
					@*<a href="index.html"><img src="~/Content/assets/img/logo_main_white.png" alt="" height="15" width="71" /></a>*@
				</div>

				<!-- secondary sidebar switch -->
				<a href="#" id="sidebar_secondary_toggle" class="sSwitch sSwitch_right sidebar_secondary_check">
					<span class="sSwitchIcon"></span>
				</a>

				<div class="uk-navbar-flip">
					<ul class="uk-navbar-nav user_actions">
						<li data-uk-dropdown="{mode:'click',pos:'bottom-left'}">
							<a href="#" class="user_action_image"><img class="md-user-image" src="~/Content/assets/img/avatars/avatar_11_tn.png" alt="" /></a>
							<div class="uk-dropdown uk-dropdown-small">
								<ul class="uk-nav js-uk-prevent">
                                    <li style="text-align: right;"></li>
									<li style="text-align: right;">@Html.ActionLink("خانه","Index","Home")</li>
									<li style="text-align: right;">@Html.ActionLink("اطلاعات کاربری", "Index", "UserProfile")</li>
									<li style="text-align: right;">@Html.ActionLink("تغییر رمز", "ChangePassword", "UserProfile")</li>
									<li style="text-align: right;">@Html.ActionLink("خروج", "Signout", "Home")</li>
								</ul>
							</div>
						</li>
					</ul>
				</div>
                <div class="uk-navbar-flip" 
                     style="margin-top:1%;color:#d9d9d9">
                    @ViewBag.UserName
                </div>

			</nav>
		</div>
	</header><!-- main header end -->

	<div id="page_content">
		<div id="page_content_inner">
			@RenderBody()
		</div>
	</div>
	<!-- google web fonts -->
	<script>
		WebFontConfig = {
			google: {
				families: [
                    'Source+Code+Pro:400,700:latin',
                    'Roboto:400,300,500,700,400italic:latin'
				]
			}
		};
		(function () {
			var wf = document.createElement('script');
			wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
            '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
			wf.type = 'text/javascript';
			wf.async = 'true';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(wf, s);
		})();
	</script>
	<!-- common functions -->
	<script src="~/Content/assets/js/common.min.js"></script>
	<!-- uikit functions -->
	<script src="~/Content/assets/js/uikit_custom.min.js"></script>
	<!-- altair common functions/helpers -->
	<script src="~/Content/assets/js/altair_admin_common.min.js"></script>

	<script>
		$(function () {
			// enable hires images
			altair_helpers.retina_images();
			// fastClick (touch devices)
			if (Modernizr.touch) {
				FastClick.attach(document.body);
			}
		});
	</script>

	<div id="style_switcher">
		<div id="style_switcher_toggle"><i class="material-icons">&#xE8B8;</i></div>
		<div class="uk-margin-medium-bottom">
			<h4 class="heading_c uk-margin-bottom">Colors</h4>
			<ul class="switcher_app_themes" id="theme_switcher">
				<li class="app_style_default active_theme" data-app-theme="">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_a" data-app-theme="app_theme_a">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_b" data-app-theme="app_theme_b">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_c" data-app-theme="app_theme_c">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_d" data-app-theme="app_theme_d">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_e" data-app-theme="app_theme_e">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_f" data-app-theme="app_theme_f">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_g" data-app-theme="app_theme_g">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_h" data-app-theme="app_theme_h">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
				<li class="switcher_theme_i" data-app-theme="app_theme_i">
					<span class="app_color_main"></span>
					<span class="app_color_accent"></span>
				</li>
			</ul>
		</div>
	</div>
	<script>
		$(function () {
			var $switcher = $('#style_switcher'),
                $switcher_toggle = $('#style_switcher_toggle'),
                $theme_switcher = $('#theme_switcher'),
                $mini_sidebar_toggle = $('#style_sidebar_mini'),
                $boxed_layout_toggle = $('#style_layout_boxed'),
                $accordion_mode_toggle = $('#accordion_mode_main_menu'),
                $body = $('body');


			$switcher_toggle.click(function (e) {
				e.preventDefault();
				$switcher.toggleClass('switcher_active');
			});

			$theme_switcher.children('li').click(function (e) {
				e.preventDefault();
				var $this = $(this),
                    this_theme = $this.attr('data-app-theme');

				$theme_switcher.children('li').removeClass('active_theme');
				$(this).addClass('active_theme');
				$body
                    .removeClass('app_theme_a app_theme_b app_theme_c app_theme_d app_theme_e app_theme_f app_theme_g app_theme_h app_theme_i')
                    .addClass(this_theme);

				if (this_theme == '') {
					localStorage.removeItem('altair_theme');
				} else {
					localStorage.setItem("altair_theme", this_theme);
				}

			});

			// hide style switcher
			$document.on('click keyup', function (e) {
				if ($switcher.hasClass('switcher_active')) {
					if (
                        (!$(e.target).closest($switcher).length)
                        || (e.keyCode == 27)
                    ) {
						$switcher.removeClass('switcher_active');
					}
				}
			});

			// get theme from local storage
			if (localStorage.getItem("altair_theme") !== null) {
				$theme_switcher.children('li[data-app-theme=' + localStorage.getItem("altair_theme") + ']').click();
			}


			// toggle mini sidebar

			// change input's state to checked if mini sidebar is active
			if ((localStorage.getItem("altair_sidebar_mini") !== null && localStorage.getItem("altair_sidebar_mini") == '1') || $body.hasClass('sidebar_mini')) {
				$mini_sidebar_toggle.iCheck('check');
			}

			$mini_sidebar_toggle
                .on('ifChecked', function (event) {
                	$switcher.removeClass('switcher_active');
                	localStorage.setItem("altair_sidebar_mini", '1');
                	location.reload(true);
                })
                .on('ifUnchecked', function (event) {
                	$switcher.removeClass('switcher_active');
                	localStorage.removeItem('altair_sidebar_mini');
                	location.reload(true);
                });


			// toggle boxed layout

			if ((localStorage.getItem("altair_layout") !== null && localStorage.getItem("altair_layout") == 'boxed') || $body.hasClass('boxed_layout')) {
				$boxed_layout_toggle.iCheck('check');
				$body.addClass('boxed_layout');
				$(window).resize();
			}

			$boxed_layout_toggle
                .on('ifChecked', function (event) {
                	$switcher.removeClass('switcher_active');
                	localStorage.setItem("altair_layout", 'boxed');
                	location.reload(true);
                })
                .on('ifUnchecked', function (event) {
                	$switcher.removeClass('switcher_active');
                	localStorage.removeItem('altair_layout');
                	location.reload(true);
                });

			// main menu accordion mode
			if ($sidebar_main.hasClass('accordion_mode')) {
				$accordion_mode_toggle.iCheck('check');
			}

			$accordion_mode_toggle
                .on('ifChecked', function () {
                	$sidebar_main.addClass('accordion_mode');
                })
                .on('ifUnchecked', function () {
                	$sidebar_main.removeClass('accordion_mode');
                });


		});
	</script>
</body>
</html>

Management/ApplicationStoreApplication/Views/Shared/_LayoutSecond.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mvc ViewService Sample</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="\" class="navbar-brand">Mvc ViewService Sample</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Enhanced Coding</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>