SecurityService/SecurityService.SSO/Controllers/LogonWorkflowController.cs
using System.Web.Mvc;
using IdentityServer3.Core.Models;
using IdentityServer3.Core.ViewModels;
using System.IO;
using System.Drawing;
using System;
using System.Text;
using SecurityService.SSO.Models;
using SecurityService.SSO.Services;
using IdentityServer3.Core.Services.Default;
using System.Threading.Tasks;
using SecurityService.SSO.IdentityService;
using SecurityService.SSO.Infrastructure;
using System.Runtime.Remoting.Contexts;
using System.Security.Claims;

namespace SecurityService.SSO.Controllers
{
    public class LogonWorkflowController : Controller
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogonWorkflowController"/> class.
        /// </summary>
        public LogonWorkflowController()
        {
           
        }

        #region Login

        /// <summary>
        /// Loads the HTML for the login page.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <param name="message">
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Login(LoginViewModel model, SignInMessage message)
        {
            return this.View(model);
        }

        #endregion

        #region Logout

        /// <summary>
        /// Loads the HTML for the logout prompt page.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Logout(LogoutViewModel model)
        {
            return this.View(model);
        }

        #endregion

        #region LoggedOut

        /// <summary>
        /// Loads the HTML for the logged out page informing the user that they have successfully logged out.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult LoggedOut(LoggedOutViewModel model)
        {
            return this.View(model);
        }

        #endregion

        #region Consent

        /// <summary>
        /// Loads the HTML for the user consent page.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Consent(ConsentViewModel model)
        {
            return this.View(model);
        }

        #endregion

        #region Permissions

        /// <summary>
        /// Loads the HTML for the client permissions page.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Permissions(ClientPermissionsViewModel model)
        {
            return this.View(model);
        }

        #endregion

        #region Error

        /// <summary>
        /// Loads the HTML for the error page.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public virtual ActionResult Error(ErrorViewModel model)
        {
            return this.View(model);
        }

        #endregion

        #region RecoverPass


        public ActionResult ResetPassword(LoginViewModel model)
        {
            return this.View(model);
        }


        public  ActionResult RecoverPass(string Username)
        {
            //var userName = ((ClaimsIdentity)User.Identity).FindFirst("UserName");
            var  selectedTraining = Request["Username"];
            if (Username == null)
            {
                ModelState.AddModelError("UserName", "UserName is Require");
                return  Redirect("http://localhost:16161/");
            }
           var _name =  RecoveryPassService.GetPhoneNumber(Username);
            return View("Index", Username);
        }
        #endregion

       
    }
}

SecurityService/SecurityService.SSO/Controllers/MvcCaptchaController.cs
using SecurityService.SSO.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SecurityService.SSO.Controllers
{
    public class MvcCaptchaController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string CaptchaUserInput)
        {
            var resultStr = string.Empty;
            var captchaStr = this.HttpContext.Session["Captcha"]; 
            CaptchaUserInput = CaptchaUserInput.ToLower();
            if (String.Equals(captchaStr, CaptchaUserInput))
            {
                resultStr = "Captcha is entered correctly!!";
            }
            else
            {
                resultStr = "Captcha re-enter captcha!";
            }

            return Json(new { Data = resultStr, captchaStr = captchaStr, CaptchaUserInput = CaptchaUserInput }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GenerateCaptcha()
        {
            Captcha captcha = new Captcha(6, 200, 100, HttpContext);
            return File(captcha.create_captcha(), "image/jpeg");
        }
    }
}

SecurityService/SecurityService.SSO/Controllers/RecoverPasswordController.cs
using manage = Management.Infrastructure.Service.Contracts;
using SecurityService.SSO.Services;
using System;
using System.Text;
using System.Web.Mvc;
using SecurityService.SSO.Models;
using SecurityService.SSO.Infrastructure.Configuration;

namespace SecurityService.SSO.Controllers
{
    public class RecoverPasswordController : Controller
    {
        #region Fields
        private SmsService _smsService;
        private readonly UserService _userService = new UserService();
        #endregion

        #region Ctor

        public RecoverPasswordController()
        {
            _smsService = new SmsService();
        }
        #endregion

        public ActionResult RecoverCode(string userName)
        {
            if (userName == "" || userName == null)
            {
                return Json(new { result = "نام کاربری را وارد نمایید" });
            }
            if (userName.ToLower() == "admin")
            {
                return Json(new { result = "امکان بازیابی پسورد برای این کاربر وجود ندارد" });
            }
            var _user = _userService.FindByName(userName);
            if (_user == null)
            {
                //ModelState.AddModelError("userName", "there is not userName");
                return Json(new { result = "کاربری با این نام وجود ندارد" });
            }
            var pass = CreatePassword();
            SmsService.ClsSend smsSingle = new SmsService.ClsSend();
            smsSingle.SendSMS_Single(new SmsModel { PhoneNumber = _user.PhoneNumber, Message = pass }, SmsSetting.GetConfig());
            _userService.UpdatePassword(_user, pass);
            return Json(new { result = "password recovery" });
        }

        public string CreatePassword()
        {
            int length = 8;
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder res = new StringBuilder();
            Random rnd = new Random();
            while (0 < length--)
            {
                res.Append(valid[rnd.Next(valid.Length)]);
            }
            return res.ToString();
        }

    }
}

SecurityService/SecurityService.SSO/Views/LogonWorkflow/Consent.cshtml
@model IdentityServer3.Core.ViewModels.ConsentViewModel
@{
	ViewBag.Title = "Application Consent";
}

@* This is essentially a copy of the embedded HTML that comes from IdSvr, adapted to access the Model server-side *@

<div class="row page-header">
    <div class="col-sm-10">
        @if (!string.IsNullOrWhiteSpace(Model.ClientLogoUrl))
        {
            <div class="client-logo"><img src="@Model.ClientLogoUrl"></div>
        }
        <h1>
            @Model.ClientName
            <small>is requesting your permission</small>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        @if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
        {
            <div class="alert alert-danger">
                <strong>Error:</strong>
                @Model.ErrorMessage
            </div>
        }
        <form name="form" method="post" action="@Model.ConsentUrl" class="consent-form">
            <input type="hidden" name="@Model.AntiForgery.Name" value="@Model.AntiForgery.Value" />
            <div>Uncheck the permissions you do not wish to grant.</div>
            @if (Model.IdentityScopes.Any())
            {
                <div class="panel panel-default consent-buttons">
                    <div class="panel-heading">
                        <span class="glyphicon glyphicon-user"></span>
                        Personal Information
                    </div>
                    <ul class="list-group">
                        @foreach (var scope in Model.IdentityScopes)
                        {
                            <li class="list-group-item">
                                <label>
                                    <input class="consent-scopecheck" type="checkbox" name="scopes" id="scopes_@scope.Name" value="@scope.Name" @(scope.Selected ? "checked='checked'" : "") @(scope.Required ? "disabled='disabled'" : "") />
                                    <strong>@scope.DisplayName</strong>
                                    @if (scope.Emphasize)
                                    {
                                        <span class="glyphicon glyphicon-exclamation-sign"></span>
                                    }
                                </label>
                                @if (scope.Required)
                                {
                                    <span><em>(required)</em></span>
                                }
                                @if (!string.IsNullOrWhiteSpace(scope.Description))
                                {
                                    <div class="consent-description">
                                        <label for="scopes_@scope.Name">@scope.Description</label>
                                    </div>
                                }
                            </li>
                        }
                    </ul>
                </div>
            }
            @if (Model.ResourceScopes.Any())
            {
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="glyphicon glyphicon-tasks"></span>
                        Application Access
                    </div>
                    <ul class="list-group">
                        @foreach (var scope in Model.ResourceScopes)
                        {
                            <li class="list-group-item">
                                <label>
                                    <input class="consent-scopecheck" type="checkbox" name="scopes" id="scopes_@scope.Name" value="@scope.Name" @(scope.Selected ? "checked='checked'" : "") @(scope.Required ? "disabled='disabled'" : "") />
                                    <strong>@(!string.IsNullOrWhiteSpace(scope.DisplayName) ? scope.DisplayName : scope.Description)</strong>
                                    @if (scope.Emphasize)
                                    {
                                        <span class="glyphicon glyphicon-exclamation-sign"></span>
                                    }
                                </label>
                                @if (scope.Required)
                                {
                                    <span><em>(required)</em></span>
                                }
                                @if ((!string.IsNullOrWhiteSpace(scope.Description) && !string.IsNullOrWhiteSpace(scope.DisplayName)) || scope.Required)
                                {
                                    <div class="consent-description">
                                        @if (scope.Required)
                                        {
                                            <span><em>(required)</em></span>
                                        }
                                        @if (!string.IsNullOrWhiteSpace(scope.DisplayName))
                                        {
                                            <label for="scopes_@scope.Name">@scope.Description</label>
                                        }
                                    </div>
                                }
                            </li>
                        }
                    </ul>
                </div>
            }

            @if (Model.AllowRememberConsent)
            {
                <div class="consent-remember">
                    <label>
                        <input class="consent-scopecheck" type="checkbox" name="RememberConsent" value="true" @(Model.RememberConsent ? "checked='checked'" : "") />
                        <strong>Remember My Decision</strong>
                    </label>
                </div>
            }
            <div class="consent-buttons">
                <button name="button" value="yes" class="btn btn-primary" autofocus>Yes, Allow</button>
                <button name="button" value="no" class="btn">No, Do Not Allow</button>
                @if (!string.IsNullOrWhiteSpace(Model.ClientUrl))
                {
                    <a class="pull-right btn btn-default" target="_blank" href="@Model.ClientUrl">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <strong>@Model.ClientName</strong>
                    </a>
                }
            </div>
        </form>
    </div>
</div>
@section scripts{
    @Html.Partial("_RenderAngularModel")
}

SecurityService/SecurityService.SSO/Views/LogonWorkflow/LoggedOut.cshtml
@model IdentityServer3.Core.ViewModels.LoggedOutViewModel
@{
//ViewBag.Title = "Logout";
}

@* This is essentially a copy of the embedded HTML that comes from IdSvr, adapted to access the Model server-side *@

<div class="page-header">
	<h1>
		@ViewBag.Title
        <small id="confirmation">شما از سامانه خارج شدید</small>
	</h1>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        @* New logic ensuring a consistent message if we are logging out of any applications on the IdentityServer host *@
        @if (Model.RedirectUrl == null)
        {
        <div>
            بازگشت به <a href="/">صفحه اصلی</a>
        </div>
        }
        else
        {
            if (string.IsNullOrWhiteSpace(Model.RedirectUrl))
            {
        <div>
            بازگشت به <a href="/">صفحه اصلی</a>
        </div>
            }
            else
            {
            <div>
                ورود به <a href="@Model.RedirectUrl">صفحه لاگین</a>
            </div>
            }
            foreach (var url in Model.IFrameUrls)
            {
                <iframe class="signout" src="@url" style="display: none"></iframe>
            }
        }
    </div>
</div>
@section scripts{
    @Html.Partial("_RenderAngularModel")
}

SecurityService/SecurityService.SSO/Views/LogonWorkflow/Login.cshtml
@model IdentityServer3.Core.ViewModels.LoginViewModel
@{
    ViewBag.Title = "ورود به پنل کاربری";
}
<html lang="fa">
<head>
    <link rel="icon" href="/Content/images/favicon.ico" type="image/ico">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link href="~/Content/bootstrap-rtl.min.css" rel="stylesheet" />
</head>
@*<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>*@
<body class="login-body">
    <div class="login-form container">

        <div class="row center-block">

            <div class="login-sec">
                <div class="login-textbox">

                    @if (!string.IsNullOrWhiteSpace(Model.LoginUrl))
                    {
                        @*<div class="col-md-6 col-sm-6">*@
                    if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
                    {
                            <div class="alert alert-danger">
                                <strong>خطا:</strong>
                                @Model.ErrorMessage
                            </div>
                    }
                        @*<div class="panel panel-default">*@


                        @*<h>سامانه مدیریت اطلاعات رستوران ها</h>*@
                        @*<div class="panel-heading">
                    <h3 class="panel-title">Local Login</h3>
                </div>*@

                        <form name="form" method="post" action="@Model.LoginUrl" class="form col-md-12 center-block form-horizontal">
                            <fieldset>
                                <input type="hidden" name="@Model.AntiForgery.Name" value="@Model.AntiForgery.Value" />

                                <div class="form-group login-user">
                                    <div class="user-password-style">
                                        <i class="fa fa-user fa-fw" aria-hidden="true"></i>
                                        @*<label for="username">UserName</label>*@
                                        <input required name="username" autofocus id="username" type="text" ng-model="model.username" class="form-control" placeholder="نام کاربری" value="@Model.Username" maxlength="100" @(ViewBag.DisableUserNameChange == true ? "readonly='readonly'" : "")>

                                    </div>
                                </div>

                                <div class="form-group login-password">
                                    <div class="user-password-style">
                                        <i class="fa fa-lock fa-fw" aria-hidden="true"></i>
                                        @*<label for="password">Password</label>*@
                                        <input required id="password" name="password" type="password" class="form-control text-left left-to-right" placeholder="رمز عبور" ng-model="model.password" maxlength="100" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <div class="div-center">
                                            <div class="divCaptchaContiner">
                                                <img src="@Url.Action("GenerateCaptcha", "MvcCaptcha")" , alt="Captcha Code" class="img-thumbnail" id="captchaImageID" />
                                                <img src="~/Content/images/refresh.png" class="divRefreshContainer" id="imgRefreshId" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.TextBox("CaptchaUserInput", null, new
                                       {
                                           @class = "form-control item-margin",
                                           required = "",
                                           type = "text",
                                           placeholder = "تصویر امنیتی",
                                           autocomplete = "off"
                                       })

                                        </div>
                                    </div>
                                </div>

                                @if (Model.AllowRememberMe)
                                {
                                    <div class="form-group">
                                        <label for="rememberMe">
                                            <input type="checkbox" id="rememberMe" name="rememberMe" @(Model.RememberMe ? "checked='checked'" : "") value="true">
                                            <strong>مرا به خاطر بسپار</strong>
                                        </label>
                                    </div>
                                }


                                <div class="form-group login-submit">
                                    <button class="btn btn-primary btn-default btn-block" id="login" ng-disabled="form.$invalid">ورود به سایت</button>
                                </div>
                            </fieldset>
                        </form>
                        <div class="form-group">
                            <div class="col-lg-12" style="padding-top: 10px;padding-bottom: 10px">
                                <a href="#" id="submit_link" class="button">فراموشی رمز عبور</a>
                            </div>
                        </div>
                        @*<a href="@Url.Action("RecoverCode", "RecoverPassword", new { Username = Model.Username})">فراموشی رمز عبور</a>*@
                        @*<a href="/RecoverPassword/RecoverCode">فراموشی رمز عبور</a>*@

                        @*<ul class="list-unstyled">
                    @if (Model.AdditionalLinks != null)
                    {
                        foreach (var link in Model.AdditionalLinks)
                        {
                            <li><a href="@link.Href" id="@link.Text.Replace(" ", "")">@link.Text</a></li>
                        }
                    }
                </ul>*@
                    }
                    </div>
                </div>
                @*</div>*@

           


                @if (Model.ExternalProviders != null && Model.ExternalProviders.Any())
                {
                    <div class="col-md-6 col-sm-6 external-providers">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">External Login</h3>
                            </div>
                            <div class="panel-body">
                                <ul class="list-inline">
                                    @foreach (var provider in Model.ExternalProviders)
                                    {
                                        <li>
                                            <a class="btn btn-default" href="@provider.Href">@provider.Text</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>
@section scripts{

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/Captcha.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
}

SecurityService/SecurityService.SSO/Views/LogonWorkflow/Logout.cshtml
@model IdentityServer3.Core.ViewModels.LogoutViewModel
@{
//ViewBag.Title = "خروج از سامانه";
}

@* This is essentially a copy of the embedded HTML that comes from IdSvr, adapted to access the Model server-side *@

@*<div class="page-header">
	<h1>@ViewBag.Title</h1>
</div>*@

<html >



<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="icon" href="/Content/images/favicon.ico" type="image/ico">
    <title>خروج از سامانه</title>
    
    <link href="/content/app/app.css" rel="stylesheet">
    <link href="/Content/libs/font-awesome/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/libs/Login.css" rel="stylesheet" />

    <link href="/Content/libs/ace.css" rel="stylesheet" />
</head>
<body>
    <div class="row center-block">
        <div class="login-sec">
            <div class="login-textbox">
                <h6 class="header blue lighter bigger">
                    <i class="fa fa-coffee green"></i>
                    خروج از سامانه
                </h6>
                <form name="form" method="post" action="@Model.LogoutUrl">
                    <input type="hidden" name="@Model.AntiForgery.Name" value="@Model.AntiForgery.Value" />
                    <fieldset>
                        <div class="form-group">
                            <button class="btn width-35 pull-left btn btn-small btn-primary" id="yes">تایید</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    </body>
</html>
@section scripts{
    @Html.Partial("_RenderAngularModel")
}

SecurityService/SecurityService.SSO/Views/LogonWorkflow/Permissions.cshtml
@model IdentityServer3.Core.ViewModels.ClientPermissionsViewModel
@{
	ViewBag.Title = "Application Permissions";
}

@* This is essentially a copy of the embedded HTML that comes from IdSvr, adapted to access the Model server-side *@

<div class="row page-header">
	<div class="col-sm-10">
		<h1>
			@ViewBag.Title			
		</h1>
	</div>
</div>

<div class="row">
    <div class="col-sm-8">
        @if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
        {
            <div class="alert alert-danger">
                <strong>Error:</strong>
                @Model.ErrorMessage
            </div>
        }
    </div>
    @if (!Model.Clients.Any())
    {
        <div class="col-sm-8">
            <div class="alert alert-info">
                You have not given permission to any applications
            </div>
        </div>
    }
</div>
<div class="permissions">
    @foreach (var client in Model.Clients)
    {
        <div class="row permission">
            <div class="col-sm-2">
                @if (!string.IsNullOrWhiteSpace(client.ClientLogoUrl))
                {
                    <img src="@client.ClientLogoUrl">
                }
                else
                {
                    <img src="@Url.Content("~/content/images/unknownclient.png")" width="50">
                }
            </div>
            <div class="col-sm-8">
                <div class="permission-clientname">@client.ClientName</div>
                @if (client.IdentityPermissions.Any())
                {
                    <div>
                        <div class="permission-type">Identity Permissions</div>
                        <ul>
                            @foreach (var permission in client.IdentityPermissions)
                            {
                                <li>@permission.DisplayName</li>
                            }
                        </ul>
                    </div>
                }
                @if (client.ResourcePermissions.Any())
                {
                    <div>
                        <div class="permission-type">Resource Permissions</div>
                        <ul>
                            @foreach (var permission in client.ResourcePermissions)
                            {
                                <li>
                                    @(!string.IsNullOrWhiteSpace(permission.DisplayName) ? permission.DisplayName : permission.Description)
                                </li>
                            }
                        </ul>
                    </div>
                }
            </div>
            <div class="col-sm-2">
                <form name="form" method="post" action="@Model.RevokePermissionUrl" class="consent-form">
                    <input type="hidden" name="@Model.AntiForgery.Name" value="@Model.AntiForgery.Value" />
                    <input type="hidden" name="clientId" value="@client.ClientId">
                    <button class="btn btn-danger">Revoke Access</button>
                </form>
            </div>
        </div>
    }
</div>
@section scripts{
    @Html.Partial("_RenderAngularModel")
}

SecurityService/SecurityService.SSO/Views/LogonWorkflow/ResetPassword.cshtml
@{
    ViewBag.Title = "ResetPassword";
}

<h2>ResetPassword</h2>

SecurityService/SecurityService.SSO/Views/LogonWorkflow/_RenderAngularModel.cshtml
@*
    We used to use a modified version of the IdSvr embedded HTML on all these screens,
    This used an Angular version of the model - which was rendered to the screen
    using the below.

    <script> id='modelJson' type='application/json'>
        {model}
    </script>
    <script </script>src="{applicationPath}/assets/scripts.js"></script>

    BUT, the {applicationPath}/assets/scripts.js embedded file is compiled to 
    includes the following files in order:
        ///#source 1 1 libs/jquery/jquery-1.11.0.min.js
        ///#source 1 1 libs/bootstrap/js/bootstrap.min.js
        ///#source 1 1 libs/angular/angular.1.2.13.min.js
        ///#source 1 1 libs/encoder/encoder.min.js
        ///#source 1 1 app/app.js

    Since this uses a different version of jQuery to the ones
    we're using (1.11.0 vs 2.1.3) and a different version of
    Bootstrap (3.0.3 vs 3.3.4), it breaks other JS in our solution
    (such as the Drop Down menus).

    As an alternative, we could load only the extra scripts on top of our jQuery
    and	Bootstrap (and hope that they still work with the newer versions):

    <script id='modelJson' type='application/json'>
            {model}
    </script>
    @Scripts.Render(
        "~/scripts/idsvr/libs/angular/angular.1.2.13.min.js",
        "~/scripts/idsvr/libs/encoder/encoder.min.js",
        "~/scripts/idsvr/app/app.js");

    This does currently work, but we would need to make sure we regression
    test this every time our jQuery or Bootstrap were updated. AND make
    sure we updated the IdSvr js source every time it was updated.

    Instead, since we have swapped entirely to using only a server-side
    version of the model, the angular binding is no longer used, so
    we can simply not add any scripts here.
*@